export const SHINZO = {};

/**
 * The set of Caracteristique Scores used within the system.
 * @type {Object}
 */
SHINZO.caracteristiques = {
  con: 'SHINZO.Caracteristique.Con.long',
  agi: 'SHINZO.Caracteristique.Agi.long',
  cha: 'SHINZO.Caracteristique.Cha.long',
  sav: 'SHINZO.Caracteristique.Sav.long',
  mag: 'SHINZO.Caracteristique.Mag.long',
  men: 'SHINZO.Caracteristique.Men.long',
  cor: 'SHINZO.Caracteristique.Cor.long',
  esp: 'SHINZO.Caracteristique.Esp.long',
  soc: 'SHINZO.Caracteristique.Soc.long',
  pug: 'SHINZO.Caracteristique.Pug.long',
  cac: 'SHINZO.Caracteristique.Cac.long',
  pre: 'SHINZO.Caracteristique.Pre.long',
  esq: 'SHINZO.Caracteristique.Esq.long',
  par: 'SHINZO.Caracteristique.Par.long',
  dis: 'SHINZO.Caracteristique.Dis.long',
  obs: 'SHINZO.Caracteristique.Obs.long',
  per: 'SHINZO.Caracteristique.Per.long',
  psy: 'SHINZO.Caracteristique.Psy.long',
  int: 'SHINZO.Caracteristique.Int.long',
  com: 'SHINZO.Caracteristique.Com.long',
  aut: 'SHINZO.Caracteristique.Aut.long',
  med: 'SHINZO.Caracteristique.Med.long',
  pil: 'SHINZO.Caracteristique.Pil.long',
  art: 'SHINZO.Caracteristique.Art.long',
  vit: 'SHINZO.Caracteristique.Vit.long',
  ins: 'SHINZO.Caracteristique.Ins.long',
  s_f: 'SHINZO.Caracteristique.S_f.long',
  reg: 'SHINZO.Caracteristique.Reg.long',
  rec: 'SHINZO.Caracteristique.Rec.long',
  deg_physique: 'SHINZO.Caracteristique.Dep.long',
  res_physique: 'SHINZO.Caracteristique.Rep.long',
  deg_magique: 'SHINZO.Caracteristique.Dem.long',
  res_magique: 'SHINZO.Caracteristique.Rem.long',
};

SHINZO.caracteristiquesAbbreviations = {
  con: 'SHINZO.Caracteristique.Con.abbr',
  agi: 'SHINZO.Caracteristique.Agi.abbr',
  cha: 'SHINZO.Caracteristique.Cha.abbr',
  sav: 'SHINZO.Caracteristique.Sav.abbr',
  mag: 'SHINZO.Caracteristique.Mag.abbr',
  men: 'SHINZO.Caracteristique.Men.abbr',
  cor: 'SHINZO.Caracteristique.Cor.abbr',
  esp: 'SHINZO.Caracteristique.Esp.abbr',
  soc: 'SHINZO.Caracteristique.Soc.abbr',
  pug: 'SHINZO.Caracteristique.Pug.abbr',
  cac: 'SHINZO.Caracteristique.Cac.abbr',
  pre: 'SHINZO.Caracteristique.Pre.abbr',
  esq: 'SHINZO.Caracteristique.Esq.abbr',
  par: 'SHINZO.Caracteristique.Par.abbr',
  dis: 'SHINZO.Caracteristique.Dis.abbr',
  obs: 'SHINZO.Caracteristique.Obs.abbr',
  per: 'SHINZO.Caracteristique.Per.abbr',
  psy: 'SHINZO.Caracteristique.Psy.abbr',
  int: 'SHINZO.Caracteristique.Int.abbr',
  com: 'SHINZO.Caracteristique.Com.abbr',
  aut: 'SHINZO.Caracteristique.Aut.abbr',
  med: 'SHINZO.Caracteristique.Med.abbr',
  pil: 'SHINZO.Caracteristique.Pil.abbr',
  art: 'SHINZO.Caracteristique.Art.abbr',
  vit: 'SHINZO.Caracteristique.Vit.abbr',
  ins: 'SHINZO.Caracteristique.Ins.abbr',
  s_f: 'SHINZO.Caracteristique.S_f.abbr',
  reg: 'SHINZO.Caracteristique.Reg.abbr',
  rec: 'SHINZO.Caracteristique.Rec.abbr',
  deg_physique: 'SHINZO.Caracteristique.Dep.abbr',
  res_physique: 'SHINZO.Caracteristique.Rep.abbr',
  deg_magique: 'SHINZO.Caracteristique.Dem.abbr',
  res_magique: 'SHINZO.Caracteristique.Rem.abbr',
};

SHINZO.description = {
  age: "SHINZO.Description.Age",
  genre: "SHINZO.Description.Genre",
  taille: "SHINZO.Description.Taille",
  poids: "SHINZO.Description.Poids",
  race: "SHINZO.Description.Race",
  classe: "SHINZO.Description.Classe",
  metier: "SHINZO.Description.Metier",
  loisir: "SHINZO.Description.Loisir"
}

SHINZO.activeEffectChanges = {
  "system.health.max": "PV",
  "system.power.max": "PE",
  "system.gds_stats.con.value": "SHINZO.Caracteristique.Con.abbr",
  "system.gds_stats.agi.value": 'SHINZO.Caracteristique.Agi.abbr',
  "system.gds_stats.cha.value": 'SHINZO.Caracteristique.Cha.abbr',
  "system.gds_stats.sav.value": 'SHINZO.Caracteristique.Sav.abbr',
  "system.gds_stats.mag.value": 'SHINZO.Caracteristique.Mag.abbr',
  "system.gds_stats.men.value": 'SHINZO.Caracteristique.Men.abbr',
  "system.gds_stats.con.b_m": "SHINZO.Caracteristique.ConB.abbr",
  "system.gds_stats.agi.b_m": 'SHINZO.Caracteristique.AgiB.abbr',
  "system.gds_stats.cha.b_m": 'SHINZO.Caracteristique.ChaB.abbr',
  "system.gds_stats.sav.b_m": 'SHINZO.Caracteristique.SavB.abbr',
  "system.gds_stats.mag.b_m": 'SHINZO.Caracteristique.MagB.abbr',
  "system.gds_stats.men.b_m": 'SHINZO.Caracteristique.MenB.abbr',
  "system.maitrises.cor.b_m": 'SHINZO.Caracteristique.Cor.abbr',
  "system.maitrises.esp.b_m": 'SHINZO.Caracteristique.Esp.abbr',
  "system.maitrises.soc.b_m": 'SHINZO.Caracteristique.Soc.abbr',
  "system.ss_stats.ss_stats1.pug.b_m": 'SHINZO.Caracteristique.Pug.abbr',
  "system.ss_stats.ss_stats1.cac.b_m": 'SHINZO.Caracteristique.Cac.abbr',
  "system.ss_stats.ss_stats1.pre.b_m": 'SHINZO.Caracteristique.Pre.abbr',
  "system.ss_stats.ss_stats1.esq.b_m": 'SHINZO.Caracteristique.Esq.abbr',
  "system.ss_stats.ss_stats1.par.b_m": 'SHINZO.Caracteristique.Par.abbr',
  "system.ss_stats.ss_stats1.dis.b_m": 'SHINZO.Caracteristique.Dis.abbr',
  "system.ss_stats.ss_stats1.obs.b_m": 'SHINZO.Caracteristique.Obs.abbr',
  "system.ss_stats.ss_stats1.per.b_m": 'SHINZO.Caracteristique.Per.abbr',
  "system.ss_stats.ss_stats1.psy.b_m": 'SHINZO.Caracteristique.Psy.abbr',
  "system.ss_stats.ss_stats1.int.b_m": 'SHINZO.Caracteristique.Int.abbr',
  "system.ss_stats.ss_stats2.com.b_m": 'SHINZO.Caracteristique.Com.abbr',
  "system.ss_stats.ss_stats2.aut.b_m": 'SHINZO.Caracteristique.Aut.abbr',
  "system.ss_stats.ss_stats2.med.b_m": 'SHINZO.Caracteristique.Med.abbr',
  "system.ss_stats.ss_stats2.pil.b_m": 'SHINZO.Caracteristique.Pil.abbr',
  "system.ss_stats.ss_stats2.art.b_m": 'SHINZO.Caracteristique.Art.abbr',
  "system.ss_stats.ss_stats2.vit.b_m": 'SHINZO.Caracteristique.Vit.abbr',
  "system.ss_stats.ss_stats2.ins.b_m": 'SHINZO.Caracteristique.Ins.abbr',
  "system.ss_stats.ss_stats2.s_f.b_m": 'SHINZO.Caracteristique.S_f.abbr',
  "system.ss_stats.ss_stats2.reg.b_m": 'SHINZO.Caracteristique.Reg.abbr',
  "system.ss_stats.ss_stats2.rec.b_m": 'SHINZO.Caracteristique.Rec.abbr',
}
